version: '3.3'
services:
  companionsdb:
    build:
      dockerfile: ./docker/db.dockerfile
      context: .
    image: evisita/companionsdb
    container_name: evisita-companionsdb
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=companionsdb
    networks:
      - evisita-network
  oapi-srv-companions:
    build:
      dockerfile: ./docker/srv.dockerfile
      context: .
    image: evisita/oapi-srv-companions
    container_name: evisita-oapisrvcompanions
    ports:
      - '8081:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - evisita-network
    depends_on:
      - companionsdb

networks:
  evisita-network:
    driver: bridge